// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	ZipCode string `json:"zipCode"`
	Number  string `json:"number"`
}

type Card struct {
	ID         string    `json:"id"`
	ValidUntil string    `json:"valid_until"`
	Tags       []string  `json:"tags"`
	Name       string    `json:"name"`
	User       *User     `json:"user"`
	External   *External `json:"external"`
}

type CreateCardInput struct {
	Tags         []string      `json:"tags"`
	Name         string        `json:"name"`
	PersonalData *PersonalData `json:"personalData"`
}

type External struct {
	CardID    string `json:"card_id"`
	AccountID string `json:"account_id"`
}

type PersonalData struct {
	Name       string   `json:"name"`
	LastName   string   `json:"lastName"`
	MotherName string   `json:"motherName"`
	Document   string   `json:"document"`
	BirthDate  string   `json:"birthDate"`
	Address    *Address `json:"address"`
	Phone      *Phone   `json:"phone"`
}

type Phone struct {
	Code   string `json:"code"`
	Number string `json:"number"`
}

type User struct {
	ID string `json:"id"`
}
