apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ include "coinsure-cards.fullname" . }}
spec:
  selector:
    matchLabels:
      app: coinsure-cards
  jwtRules:
    - issuer: "coinsure"
      jwksUri: http://keycloak.iam.svc.cluster.local/realms/coinsure/protocol/openid-connect/certs
      forwardOriginalToken: true
      audiences:
        - account