apiVersion: v1
kind: Service
metadata:
  name: {{ include "coinsure-cards.fullname" . }}
  labels:
    {{- include "coinsure-cards.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rest.port }}
      targetPort: http-rest
      protocol: TCP
      name: http-rest
    - port: {{ .Values.service.graphql.port }}
      targetPort: http-graphql
      protocol: TCP
      name: http-graphql
  selector:
    {{- include "coinsure-cards.selectorLabels" . | nindent 4 }}
