apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "coinsure-cards.fullname" . }}
spec:
  hosts:
    - {{ include "coinsure-cards.fullname" . }}
  http:
    - route:
        - destination:
            host: {{ include "coinsure-cards.fullname" . }}
            subset: v1